/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVocabImageRouteImport } from './routes/api/vocab-image'
import { Route as ApiLessonRouteImport } from './routes/api/lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocabImageRoute = ApiVocabImageRouteImport.update({
  id: '/api/vocab-image',
  path: '/api/vocab-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonRoute = ApiLessonRouteImport.update({
  id: '/api/lesson',
  path: '/api/lesson',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/lesson': typeof ApiLessonRoute
  '/api/vocab-image': typeof ApiVocabImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/lesson': typeof ApiLessonRoute
  '/api/vocab-image': typeof ApiVocabImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/lesson': typeof ApiLessonRoute
  '/api/vocab-image': typeof ApiVocabImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/lesson' | '/api/vocab-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/lesson' | '/api/vocab-image'
  id: '__root__' | '/' | '/api/lesson' | '/api/vocab-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLessonRoute: typeof ApiLessonRoute
  ApiVocabImageRoute: typeof ApiVocabImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocab-image': {
      id: '/api/vocab-image'
      path: '/api/vocab-image'
      fullPath: '/api/vocab-image'
      preLoaderRoute: typeof ApiVocabImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson': {
      id: '/api/lesson'
      path: '/api/lesson'
      fullPath: '/api/lesson'
      preLoaderRoute: typeof ApiLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLessonRoute: ApiLessonRoute,
  ApiVocabImageRoute: ApiVocabImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
